### ISSUE TITLE
missing path TTS/gpt_sovits

### ISSUE THREAD

**Issue by cxumol** [xduWcy/TTS#1]
Is the directory `./gpt_sovits` excluded from some git settings?

**Comment by qz233** [comment]
I'm really sorry for not checking out the issues in time. Can you describe your situation more specifically?

**Comment by qz233** [comment]
We apologize for the delay in responding to your issue. It appears that the file in question, ".gpt_sovits," is a Git repository itself, so it cannot be trace using Git. If you have further questions about the code, we will do our best to respond in a timely manner.
